---
title: "R Notebook"
output: html_notebook
---

#Chapter 6

```{r}
library(topicmodels)
library(tidytext)
library(ggplot2)
library(dplyr)
library(tidyr)
library(gutenbergr)
library(stringr)
library(scales)
```

```{r}
AssociatedPress
```
```{r}
ap_lda <- LDA(AssociatedPress, k = 2, control = list(seed = 1234))
ap_lda
class(ap_lda)
```
```{r}
ap_topics <- tidy(ap_lda, matrix = "beta")
ap_topics
```
```{r}
ap_top_terms <- ap_topics %>% 
  group_by(topic) %>% 
  top_n(n = 10, wt = beta) %>% 
  ungroup() %>% 
  arrange(topic, -beta)
ap_top_terms
```
```{r}
ap_top_terms %>% 
  ggplot(aes(reorder(term, beta), beta, fill = factor(topic))) +
  geom_col(show.legend = F) +
  xlab("Terms") +
  facet_wrap(~ topic, scales = "free") +
  coord_flip()
```
```{r}
beta_spread <- ap_topics %>% 
  mutate(topic = paste0("topic", topic)) %>% 
  spread(key = topic, value = beta) %>% 
  filter(topic1 > 0.001 | topic2 > 0.001) %>% 
  mutate(log_ratio = log2(topic2 / topic1))
beta_spread
```
```{r}
beta_spread %>% 
  top_n(n = 20, wt = abs(log_ratio)) %>% 
  ggplot(aes(reorder(term, log_ratio), log_ratio, fill = log_ratio > 0)) +
  geom_col(show.legend = F) +
  xlab("Terms") +
  coord_flip()
```
```{r}
ap_documents <- tidy(ap_lda, matrix = "gamma") #输出包含各主题的比例
ap_documents
ap_documents %>% 
  arrange(document, topic) #各主题相加比例为1
```
```{r}
tidy(AssociatedPress) %>% 
  filter(document == 6) %>% 
  arrange(-count)
```
```{r}
titles <- c("Twenty Thousand Leagues under the Sea",
            "The War of the Worlds",
            "Pride and Prejudice",
            "Great Expectations")
books <- gutenberg_works(title %in% titles) %>% 
  gutenberg_download(meta_fields = "title") #把title列也下载下来
books
```
```{r}
by_chapter <- books %>% 
  group_by(title) %>% 
  mutate(chapter = cumsum(str_detect(text, regex("^chapter ", ignore_case = T)))) %>% 
  ungroup() %>% 
  filter(chapter > 0) %>% 
  unite(col = document, title, chapter) #新建document列，为title和chapter合并
by_chapter
```
```{r}
by_chapter_word <- by_chapter %>% 
  unnest_tokens(input = text, output = word)
by_chapter_word
```
```{r}
word_counts <- by_chapter_word %>% 
  anti_join(stop_words, by = "word") %>% 
  count(document, word, sort = T)
word_counts
```
```{r}
chapters_dtm <- word_counts %>% 
  cast_dtm(document = document, term = word, value = n)
chapters_dtm
```
```{r}
chapters_lda <- LDA(chapters_dtm, k = 4, control = list(seed = 1234))
chapters_lda
```
```{r}
chapter_topics <- tidy(chapters_lda, matrix = "beta")
chapter_topics
```
```{r}
top_terms <- chapter_topics %>% 
  group_by(topic) %>% 
  top_n(n = 5, wt = beta) %>% 
  arrange(topic, -beta)
top_terms
```
```{r}
top_terms %>% 
  ggplot(aes(reorder(term, beta), beta, fill = factor(topic))) +
  geom_col(show.legend = F) +
  xlab("Term") +
  facet_wrap(~ topic, nrow = 2, scales = "free") +
  coord_flip()
```
```{r}
chapters_gamma <- tidy(chapters_lda, matrix = "gamma")
chapters_gamma %>% 
  arrange(document, topic)
```
```{r}
chapters_gamma <- chapters_gamma %>% 
  separate(col = document, into = c("title", "chapter"), sep = "_", convert = T) #将字符转为数值
chapters_gamma
```
```{r}
chapters_gamma %>% 
  mutate(title = reorder(title, gamma * topic))

chapters_gamma %>% 
  mutate(title = reorder(title, gamma * topic)) %>% 
  ggplot(aes(factor(topic), gamma)) +
  geom_boxplot() +
  facet_wrap(~ title)
```
```{r}
chapter_classifications <- chapters_gamma %>% 
  group_by(title, chapter) %>% 
  top_n(n = 1, wt = gamma) %>% 
  ungroup
chapter_classifications
```
```{r}
book_topics <- chapter_classifications %>% 
  count(title, topic) %>% 
  group_by(title) %>% 
  top_n(n = 1, wt = n) %>% 
  ungroup() %>% 
  transmute(consensus = title, topic)
book_topics
```
```{r}
chapter_classifications %>% 
  inner_join(book_topics, by = "topic") %>% 
  filter(title != consensus)
```
```{r}
assignments <- augment(chapters_lda, data = chapters_dtm)
assignments
```
```{r}
assignments <- assignments %>% 
  separate(document, c("title", "chapter"), sep = "_", convert = T) %>% 
  inner_join(book_topics, by = c(".topic" = "topic"))
assignments
```
```{r}
assignments %>% 
  count(title, consensus, wt = count) %>% 
  group_by(title) %>% 
  mutate(percent = n / sum(n)) %>% 
  ggplot(aes(consensus, title, fill = percent)) +
  geom_tile() +
  scale_fill_gradient2(high = "red", label = percent_format()) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid = element_blank()) +
  labs(x = "Book words were assigned to",
       y = "Book words came from",
       fill = "% of assignments")
```
```{r}
wrong_words <- assignments %>% 
  filter(title != consensus)
wrong_words
```
```{r}
wrong_words %>% 
  count(title, consensus, term, wt = count) %>% 
  ungroup() %>% 
  arrange(-n)
```
```{r}
word_counts %>% 
  filter(word == "flopson")
```

