---
title: "R Notebook"
output: html_notebook
---

#Chapter 3

```{r}
pacman::p_load(dplyr, janeaustenr, tidytext)
library(ggplot2)
library(gutenbergr)
library(stringr)
```

```{r}
book_words <- austen_books() %>% 
  unnest_tokens(input = text, output = word) %>% 
  count(book, word, sort = T) %>%  #=  group_by(book) %>% count(word, sort = T)
  ungroup() #每本书中每个单词的频次
book_words

total_words <- book_words %>% 
  group_by(book) %>% 
  summarise(total = sum(n)) #每本书的总词数
total_words

book_words <- left_join(book_words, total_words, by = "book")
book_words
```
```{r}
ggplot(book_words, aes(n / total, fill = book)) +
  geom_histogram(show.legend = F, bins = 30) +
  xlim(NA, 0.0009) +
  facet_wrap(~ book, ncol = 2, scales = "free_y")
```
```{r}
freq_by_rank <- book_words %>% 
  group_by(book) %>% 
  mutate(rank = row_number(),  #每个词在在每本书中的排名
         term_frequency = n / total)
freq_by_rank
```
```{r}
freq_by_rank %>% 
  ggplot(aes(rank, term_frequency, color = book)) +
  geom_line(size = 1.1, alpha = 0.8, show.legend = F) +
  scale_x_log10() +
  scale_y_log10()

freq_by_rank %>% 
  ggplot(aes(rank, term_frequency, color = book)) +
  geom_line(size = 1.1, alpha = 0.8, show.legend = F)
```
```{r}
rank_subset <- freq_by_rank %>% 
  filter(rank < 500, rank > 10)
rank_subset
lm(log10(term_frequency) ~ log10(rank), data = rank_subset)
```
```{r}
freq_by_rank %>% 
  ggplot(aes(rank, term_frequency, color = book)) +
  geom_abline(intercept = -0.6226, slope = -1.1125, color = "gray50", linetype = 2) + #拟合直线
  geom_line(size = 1.1, alpha = 0.8, show.legend = F) +
  scale_x_log10() +
  scale_y_log10()
```
```{r}
book_words <- book_words %>% bind_tf_idf(term = word, document = book, n = n)
book_words
```
```{r}
book_words %>% 
  select(-total) %>% 
  arrange(desc(tf_idf))
```
```{r}
book_words %>% 
  arrange(desc(tf_idf)) %>% 
  group_by(book) %>% 
  top_n(wt = tf_idf, 15) %>% 
  ungroup() %>% 
  ggplot(aes(reorder(word, tf_idf), tf_idf, fill = book)) +
  geom_col(show.legend = F) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~ book, ncol = 2, scales = "free") +
  coord_flip()

book_words %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(word = factor(word, levels = rev(unique(word)))) %>% #类似reorder的作用
  group_by(book) %>% 
  top_n(wt = tf_idf, 15) %>% #按哪个变量计算top
  ungroup() %>% 
  ggplot(aes(word, tf_idf, fill = book)) +
  geom_col(show.legend = F) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~ book, ncol = 2, scales = "free") +
  coord_flip()
```
```{r}
physics <- gutenberg_download(c(37729, 14725, 13476, 5001), #5001下不到
                              meta_fields = "author") #把meta数据中author列也加上
physics
```
```{r}
physics_words <- physics %>% 
  unnest_tokens(input = text, output = word) %>% 
  count(author, word, sort = T) %>% 
  ungroup()
physics_words
```
```{r}
plot_physics <- physics_words %>% 
  bind_tf_idf(word, author, n) %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  mutate(author = factor(author, levels = c("Galilei, Galileo", "Huygens, Christiaan", "Tesla, Nikola")))

plot_physics %>% 
  group_by(author) %>% 
  top_n(n = 15, wt = tf_idf) %>% 
  ungroup %>% 
  ggplot(aes(reorder(word, tf_idf), tf_idf, fill = author)) +
  geom_col(show.legend = F) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~ author, ncol = 3, scales = "free") +
  coord_flip()
```
```{r}
physics %>% 
  filter(str_detect(text, "AK")) %>%
  select(text)
```
```{r}
mystopwords <- data_frame(word = c("eq", "co", "rc", "ac", "ak", "bn",
                                   "fig", "file", "cg", "cb", "cm"))
physics_words <- anti_join(physics_words, mystopwords, by = "word")
plot_physics <- physics_words %>% 
  bind_tf_idf(term = word, document = author, n = n) %>% 
  arrange(desc(tf_idf)) %>% 
  group_by(author) %>% 
  top_n(15, tf_idf) %>% 
  ungroup()
plot_physics
```
```{r}
ggplot(plot_physics, aes(reorder(word, tf_idf), tf_idf, fill = author)) +
  geom_col(show.legend = F) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~ author, ncol = 3, scales = "free") +
  coord_flip()
```
```{r}
gutenberg_metadata
gutenberg_metadata %>% 
  filter(gutenberg_id == 5001)
gutenberg_download(gutenberg_id = 5001, )
```

